-- Baseline marker.
--
-- database/schema.sql already creates the full v1 schema idempotently
-- (CREATE TABLE IF NOT EXISTS), so this migration records only the fact that
-- the baseline exists.  Migrations are applied in lexicographic order by
-- `python -m app.cli db-migrate` and every applied version is recorded in the
-- `schema_migrations` table.
--
-- Do not edit this file after it has been released.  Add a new numbered file
-- instead, e.g. 0003_add_cashier_shifts.sql.
INSERT OR IGNORE INTO schema_migrations (version, description)
VALUES ('0001', 'baseline created by database/schema.sql');

PRAGMA foreign_keys = ON;
